services:
  php-dev:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    restart: unless-stopped
    build:
      context: docker
      dockerfile: Php.Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./backend:/var/www/backend/
      - ./backend/storage/temp/phpunit:/opt/phpstorm-coverage

  node-spec:
    container_name: ${COMPOSE_PROJECT_NAME}-node
    restart: unless-stopped
    build:
      context: docker
      dockerfile: Node.Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./:/var/www/
